[package]
name = "nostr-blossom"
version = "0.41.0"
edition = "2021"
description = "A library for interacting with the Blossom protocol"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "blossom"]

[dependencies]
base64.workspace = true
nostr = { workspace = true, features = ["std"] }
reqwest = { workspace = true, default-features = false, features = ["json", "rustls-tls", "socks"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
